#%RAML 1.0 DataType

type: object
properties:
  firstName:
    description: This element will define firstname of employee.
    type: string
    required: true
    example: "Prajwal"
  lastName:
    description: This element will define lastname of employee.
    type: string
    required: true
    example: "Wankhade"
  email:
    description: This element will define email of employee.
    type: string
    required: false
    example: "abc@gmail.com"
  phoneNumber:
    description: This element will define phoneNumber of employee.
    type: string
    required: false
    example: "123456789"
  Designation:
    description: This element will define Designation of employee.
    type: string
    required: false
    example: "Consultant"
  Specialization:
    description: This element will define Specialization of employee.
    type: string
    required: false
    example: "Java Developer"
  country:
    description: This element will define country of employee.
    type: string
    required: false
    example: "India"
  city:
    description: This element will define city of employee.
    type: string
    required: false
    example: "Amravati"