#%RAML 1.0 DataType

type: object
properties:
  msg:
    type: string
    required: true
    example: "successful operation"
  code:
    type: integer
    required: true
    example: 200 
  success:
    type: string
    required: true
    example: "true"